### ISSUE TITLE
[Request] Show game status

### ISSUE THREAD

**Issue by FarukGamer** [mgerb/ServerStatus#1]
First I would like to tell you that you have made a super status bot.
It works great on other servers as well. My question would be, could you perhaps add a function which allows the bot to admit a game name, such as http://prntscr.com/er8os5 ?

**Comment by mgerb** [comment]
Thanks for taking the time to make a request! Glad to hear it's working! I haven't put a ton of work into it as I am not really using it right now, but I'm willing to add new features if they are reasonable. I'll also take pull requests if you are into that sort of thing.

As far as admitting the game, yes. It's possible, but what are the intentions of this functionality? Update the game name dynamically or display a game name based on a parameter in the config file?

**Comment by FarukGamer** [comment]
Thank you for implementing the request and thank you for replying. 

But unfortunately I cannot make any PR's because I haven't  learned the go language yet (using lua). Since you're using the Port scan method, it's easily to lookup the online status of the servers.

I've tested it on Source based servers like TF2, CS:GO and Garry's Mod, it should also would with others too.
But it seems that Teamspeak 3 servers cannot be looked up, there using ICMP instead of UDP/TCP. 

For the Game names. It depending on the end user how he is gonna use. May some wanna use Dynamics game names or static game names. I would prefer for Static since it just needs to show the role of the Bot and the command. ( <some text> | !ServerStatus ).

**Comment by mgerb** [comment]
Right now I just added it to the config file. Thanks for the info! I'm going to close this issue. If anything else comes up feel free to open another!
