### ISSUE TITLE
Fivem, and problems

### ISSUE THREAD

**Issue by CChampa** [mgerb/ServerStatus#10]
I am having trouble installing the bot on my server, I configured the config.json, I ran the .exe but it did not result in anything. I'm a beginner in theses things.
and wanted to know if it Works on the FiveM Server

Excuse my English, don't speak english

**Comment by mgerb** [comment]
Something in your configuration is probably wrong and it's closing before you get any output. Open the folder in CMD or Powershell and execute the .exe from there. This will keep the window open and show you the error output.

**Comment by CChampa** [comment]
ServerStatus-windows.exe: The term 'ServerStatus-windows.exe' is not recognized as a cmdlet name, function, file
the script or operable program. Check a spelling of the name or it is fine, see if the path
is correct and try again.

No linha:1 caractere:1
+ ServerStatus-windows.exe
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (ServerStatus-windows.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Shows this

**Comment by mgerb** [comment]
Make sure you are in the directory and run it with `.\ServerStatus-windows.exe`

**Comment by CChampa** [comment]
The config.json and the .exe, have to be inside the ServerStatus folder?

**Comment by mgerb** [comment]
The config and executable must be in the same folder. Doesn't matter the folder name. As far as executing it please read this https://stackoverflow.com/questions/8939897/how-do-you-run-executable-files-on-windows-7-using-the-command-prompt

**Comment by CChampa** [comment]
Reading config file...
File error: open ./config.json: The system cannot find the specified file.

He's in the same place as the StatusServer

**Comment by mgerb** [comment]
You MUST be executing this from the current directory that it is in because that is where it tries to read the config.json file.

- open cmd/powershell
- cd into the directory
- `.\ServerStatus-window.exe

If that doesn't work I don't know how else to help you.
