### ISSUE TITLE
cannot find package ...

### ISSUE THREAD

**Issue by Manoz** [mgerb/ServerStatus#2]
Hey,

After cloning your packages, I started the `make all` command. 
I have Go installed of course. Any idea how to solve this?

<img width="735" alt="screen shot 2017-06-11 at 17 50 32" src="https://user-images.githubusercontent.com/1554207/27012370-aa11212c-4ece-11e7-9858-5353cdf885c4.png">

**Comment by mgerb** [comment]
Make sure you have your GOPATH set up properly.

I typically have something like this in my .bashrc file.

```
export GOPATH=/home/go
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOBIN
```

**Comment by Manoz** [comment]
Hum indeed.
`$ go get github.com/bwmarrin/discordgo` and `$ go get github.com/anvie/port-scanner` did work. Thank you :)
