### ISSUE TITLE
Running exe

### ISSUE THREAD

**Issue by lferezy4** [mgerb/ServerStatus#20]
when i try to run the exe it just opens a command window and then goes away. is there any 3rd party software i need installed for this to work?

**Comment by mgerb** [comment]
No 3rd party software is required. Something is likely off in your config. If you open the command prompt or powershell in the directory of the bot and run it by typing the full bot name exe file, it will stay open and show you the error message.

I think I need to add something for windows users to keep the command prompt open if it panics.

**Comment by lferezy4** [comment]
Does it generate the config? 

> c:\Users\Administrator\Documents\Status>ServerStatus.exe
Starting Server Status v0.4.0
Reading config file...
2018/08/22 20:58:06 File error: open ./config.json: The system cannot find the file specified.

c:\Users\Administrator\Documents\Status>
It didnt generate it for me...

**Comment by mgerb** [comment]
It does not generate the config for you. [Download it from here](https://github.com/mgerb/ServerStatus/releases/download/v0.4.0/config.json), fill in your own configurations, then make sure it is in the same directory as the bot exe.

**Comment by mgerb** [comment]
I assume you have figured this out so I'm closing.
