### ISSUE TITLE
Keeping it running

### ISSUE THREAD

**Issue by darrkwolf** [mgerb/ServerStatus#22]
I am trying to have the bot set up pretty much permanently. However when i run the ServerStatus-linux file it boots the bot but then shuts down later after i close the SSH client. Is there a way to have it start up when the server does and run permanently?

I am running this on an external server (hosted VPS) with root access over ssh. Server information:
> Server: Linux 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Many thanks

**Comment by mgerb** [comment]
I use [tmux](https://github.com/tmux/tmux) for this. It's a terminal multiplexer. Basically it allows you to keep a terminal session open and attach/detach to it.
