### ISSUE TITLE
Windows Specific Binary Does Not work 

### ISSUE THREAD

**Issue by gothicdude1044** [mgerb/ServerStatus#26]
I have managed to get this to run via CMD on Windows but when it looks for config even if i point it to where it is it still states cannot find ./config.json i was not able to get this working in docker either

**Comment by mgerb** [comment]
The `config.json` must be in the same directory where the executable is run from.

**Comment by gothicdude1044** [comment]
I've done that it's in the folder with the executable

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gothicdude1044** [comment]
D:\serverstatus>ServerStatus-windows.exe
Starting Server Status v0.6.0
Reading config file...
error obtaining account details, HTTP 401 Unauthorized, {"message": "401: Unauthorized", "code": 0}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x606c53]
 this is error im getting now

**Comment by gothicdude1044** [comment]
I thnik i Fixed it now my windows system was blocking it
