### ISSUE TITLE
Server status is not working.

### ISSUE THREAD

**Issue by RaspberryTech01** [mgerb/ServerStatus#33]
Hi, I have tried both the linux binary and the docker-compose. The bot comes online and can read the config.json file. When I try to use !ServerStatus or automatically wait for it to post servers in the channel ID channel, nothing comes even after 10 seconds. 
![image](https://user-images.githubusercontent.com/31044433/94476087-e65e6e00-01c7-11eb-9df8-6e847b93b8ac.png)

The image is of my config file. Both the linux and docker binary work but I am unable to use commands or get the server statuses.

How can I fix this?

**Comment by mgerb** [comment]
Does the bot send the initial welcome message to the DIscord chat channel on startup? If not, it sounds like your bot may not have been added to your server yet. Try this https://discordjs.guide/preparations/adding-your-bot-to-servers.html

**Comment by RaspberryTech01** [comment]
Ah right that solved it I needed to grant it administrator permissions, a question, is it possible to it show the uptime automatically lets say every 5 minutes? Rather than me manually having to type the command?

**Comment by RaspberryTech01** [comment]
https://github.com/mgerb/ServerStatus/issues/32
Question above answered here.
