### ISSUE TITLE
Embedded box

### ISSUE THREAD

**Issue by Hyakkimaru** [mgerb/ServerStatus#9]
Hi ! Thank you for your bot, it's working like a charm !

I have a simple question for you, will you add embedded messages on the bot ? It could be nice to have some fancy boxes when he talks to us :) ! (like, a box with red bar when the server goes offline and a green bar when it's online !)

Thank you anyway, you're the best !

**Comment by mgerb** [comment]
Thanks for the suggestion! I may add this in the future.

**Comment by mgerb** [comment]
I updated the new release, check it out here :) https://github.com/mgerb/ServerStatus/releases/tag/0.3.0
